// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:canopy/data/models/app_settings.dart';
import 'package:canopy/data/models/commitment_block.dart';
import 'package:canopy/data/models/completion_log.dart';
import 'package:canopy/data/models/daily_schedule.dart';
import 'package:canopy/data/models/goal.dart';
import 'package:canopy/data/models/quarterly_snapshot.dart';
import 'package:canopy/data/models/restorative_item.dart';
import 'package:canopy/data/models/scheduled_chunk.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CommitmentBlockAdapter());
    registerAdapter(CompletionLogAdapter());
    registerAdapter(DailyScheduleAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(QuarterlySnapshotAdapter());
    registerAdapter(RestorativeItemAdapter());
    registerAdapter(ScheduledChunkAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CommitmentBlockAdapter());
    registerAdapter(CompletionLogAdapter());
    registerAdapter(DailyScheduleAdapter());
    registerAdapter(GoalAdapter());
    registerAdapter(QuarterlySnapshotAdapter());
    registerAdapter(RestorativeItemAdapter());
    registerAdapter(ScheduledChunkAdapter());
  }
}
