#!/usr/bin/env bash
# The only supported way to build Canopy's iOS target.
#
# WHY THIS EXISTS
# ----------------
# The Google OAuth client id (CALAUTH-01/CALAUTH-04, plan 36-04) has to reach
# two places that need it — the Dart dart-define GOOGLE_IOS_CLIENT_ID
# (lib/data/calendar/google_oauth_config.dart) and the iOS URL-scheme
# registration (ios/Runner/Info.plist's CFBundleURLTypes, via a build setting
# in the generated ios/Flutter/GoogleOAuth.xcconfig) — from ONE gitignored
# source, .google-client-id, and NEVER as a committed literal. This script is
# what makes both agree, deriving the reversed scheme with the same rule
# lib/data/calendar/google_oauth_config.dart's reverseGoogleClientId() uses
# (checked for agreement by test/tools/build_ios_wrapper_test.dart).
#
# A build attempted without .google-client-id fails HERE, before flutter is
# ever invoked, rather than shipping a sign-in button that silently does
# nothing — the trap this phase's CONTEXT names explicitly.
#
# USAGE
# -----
#   tools/build-ios.sh [build|run] [any other flutter args...]
#     tools/build-ios.sh                  # flutter build ios
#     tools/build-ios.sh run --release    # flutter run --release
#     tools/build-ios.sh build --simulator --no-codesign
#
# Don't have .google-client-id yet? See
# .planning/phases/36-connect-google-calendar-without-hunting-for-a-url/36-GOOGLE-CLOUD-SETUP.md

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLIENT_ID_FILE="$REPO/.google-client-id"
XCCONFIG_OUT="$REPO/ios/Flutter/GoogleOAuth.xcconfig"
SETUP_DOC=".planning/phases/36-connect-google-calendar-without-hunting-for-a-url/36-GOOGLE-CLOUD-SETUP.md"
SUFFIX=".apps.googleusercontent.com"

fail() {
  echo "ERROR: $1" >&2
  exit 1
}

if [[ ! -f "$CLIENT_ID_FILE" ]]; then
  fail "$CLIENT_ID_FILE not found.

Get your iOS OAuth client id from Google Cloud Console (APIs & Services ->
Credentials -> your iOS client, ends in $SUFFIX) and:

  echo '<your-client-id>$SUFFIX' > .google-client-id
  chmod 600 .google-client-id

See $SETUP_DOC for the full walkthrough."
fi

CLIENT_ID="$(tr -d '[:space:]' < "$CLIENT_ID_FILE")"

if [[ -z "$CLIENT_ID" ]]; then
  fail "$CLIENT_ID_FILE is empty. See $SETUP_DOC."
fi

if [[ "$CLIENT_ID" != *"$SUFFIX" || "${#CLIENT_ID}" -le "${#SUFFIX}" ]]; then
  fail "$CLIENT_ID_FILE does not look like a Google OAuth client id (expected it to end in $SUFFIX). See $SETUP_DOC."
fi

ID_PART="${CLIENT_ID%$SUFFIX}"
XCCONFIG_KEY="GOOGLE_REVERSED_CLIENT_ID"
REVERSED_PREFIX="com.googleusercontent.apps."
REVERSED_VALUE="$REVERSED_PREFIX$ID_PART"

# Generated file — never edit by hand, never commit (see .gitignore). Mirrors
# reverseGoogleClientId() in lib/data/calendar/google_oauth_config.dart; the
# agreement between the two is proven by test/tools/build_ios_wrapper_test.dart.
{
  printf '// GENERATED by tools/build-ios.sh from .google-client-id.\n'
  printf '// Do not edit by hand or commit — see .gitignore.\n'
  printf '%s = %s\n' "$XCCONFIG_KEY" "$REVERSED_VALUE"
} > "$XCCONFIG_OUT"

# Research's Pitfall 4: the bundle ID changed mid-phase under D-36-02, and a
# drift between Cloud Console and the built app surfaces as an unhelpful
# client error or a consent sheet that never completes. Print it so a
# mismatch is a five-second visual check rather than a confusing failure.
# Guarded by file existence so the generate-only test path (no fake xcodeproj
# in its temp dir) doesn't need to fake this file too.
PBXPROJ="$REPO/ios/Runner.xcodeproj/project.pbxproj"
if [[ -f "$PBXPROJ" ]]; then
  BUNDLE_ID="$(grep 'PRODUCT_BUNDLE_IDENTIFIER = ' "$PBXPROJ" \
    | grep -v RunnerTests \
    | head -1 \
    | sed -E 's/.*PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);.*/\1/' \
    | tr -d ' ')"
  echo "Building for bundle identifier: $BUNDLE_ID"
  echo "Make sure your Cloud Console iOS OAuth client is registered against exactly that bundle ID."
fi

# test/tools/build_ios_wrapper_test.dart sets this to stop right here —
# `flutter test` must never shell out to a real `flutter build`/`flutter run`.
if [[ "${BUILD_IOS_WRAPPER_GENERATE_ONLY:-}" == "1" ]]; then
  exit 0
fi

MODE="${1:-build}"
if [[ $# -gt 0 ]]; then
  shift
fi

case "$MODE" in
  build)
    flutter build ios --dart-define=GOOGLE_IOS_CLIENT_ID="$CLIENT_ID" "$@"
    ;;
  run)
    flutter run --dart-define=GOOGLE_IOS_CLIENT_ID="$CLIENT_ID" "$@"
    ;;
  *)
    fail "unknown mode '$MODE' (expected 'build' or 'run')"
    ;;
esac
